# Generated by Django 2.2.1 on 2020-11-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Master_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('sub_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sub_name', models.CharField(max_length=128)),
                ('weight', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Boy_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vehicle_insured', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_explosive', models.BooleanField()),
                ('is_hazardous', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('role_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=128)),
                ('number_plate', models.CharField(max_length=128)),
                ('rc_number', models.CharField(max_length=128)),
                ('vehicle_insurance', models.CharField(max_length=128)),
                ('manufacture_date', models.DateField()),
                ('puc', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='User_Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('reason_type', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('is_approved', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=128)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhaar_card_number', models.CharField(max_length=16)),
                ('license', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Gas_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('is_empty', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('business_type', models.CharField(max_length=128)),
                ('delivery_type', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
                ('cylinder_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.Cylinder_Master')),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.Delivery_Boy_Data')),
            ],
        ),
        migrations.CreateModel(
            name='New_or_Emergency_Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_amount', models.IntegerField()),
                ('gas_tank_amount', models.IntegerField()),
                ('is_rental', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Gas_Distributor_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=128)),
                ('total_cylinders', models.IntegerField()),
                ('total_filler_cylinders', models.IntegerField()),
                ('total_empty_cylinders', models.IntegerField()),
                ('total_godown_filled_cylinders', models.IntegerField()),
                ('total_godown_empty_cylinders', models.IntegerField()),
                ('total_vehicle_filled_cylinders', models.IntegerField()),
                ('total_vehicle_empty_cylinders', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
                ('cylinder_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.Cylinder_Master')),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User_Expense')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_master_id', models.CharField(max_length=128)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.Distributor')),
            ],
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User'),
        ),
        migrations.CreateModel(
            name='Delivery_Boy_Vehicle_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='delivery_boy_data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User'),
        ),
        migrations.CreateModel(
            name='Banker_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.User')),
            ],
        ),
    ]
