# Generated by Django 2.2.1 on 2020-11-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RautsApp_app', '0002_auto_20201120_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
