# Generated by Django 2.2.1 on 2020-11-25 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RautsApp_app', '0003_auto_20201125_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128)),
                ('role_id', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='banker_detail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='delivery_boy_data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='delivery_boy_vehicle_data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='gas_distributor_material',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='new_or_emergency_connection',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='sales_gas_data',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='user_expense',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='user_leave',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RautsApp_app.CustomUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
